name: Network Test

on: workflow_dispatch

jobs:
  test-network:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install mtr-tiny

    - name: Run network-test.sh
      run: bash ./network-test.sh
      # This step assumes network-test.sh is executable and in the root directory of the repository
